### ISSUE TITLE
Default code value for empty challanges

### ISSUE THREAD

**Issue by ivanhuay** [open-challenge/open-challenge-api#1]
You should add an empty function with name `test` so the first run or edition isn't empty.

```javascript
function test() {

}
```

**Comment by HernanGH** [comment]
How I can assigned me this issue? @ivanhuay

**Comment by ivanhuay** [comment]
@HernanGH i don't know i can see the assignees input on the right corner

**Comment by HernanGH** [comment]
Thanks!

**Comment by ivanhuay** [comment]
PR merged
